UserInterface/ViewModels/BookViewModel.cs
using BusinessLogic.Dto;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using UserInterface.Mappings;

namespace UserInterface.ViewModels.Entities
{
    public class BookViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        public string ImageSource { get; set; }
        public IFormFile Image { get; set; }
        [Required]
        public int UserId { get; set; }
        public int Rate { get; set; }
        [Required]
        public bool IsBorrowed { get; set; }
        [Required]
        public bool InGoodCondition { get; set; } = true;
        [Required]
        public bool IsPainted { get; set; } = false;
        public List<CommentDto> Comments { get; set; }
        public bool RemoveImage { get; set; }
        public DateTime CreatedDate { get; set; }
        public UserDto User { get; set; }
    }
}

UserInterface/Controllers/Api/BookController.cs
using AutoMapper;
using BusinessLogic.Dto;
using BusinessLogic.Services.BusinessService;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using UserInterface.ViewModels;

namespace UserInterface.Controllers.Api
{
    public class BookController : EbsApiController
    {
        public BookController(IBookBusinessService bookBusinessService, 
            IUserBusinessService userBusinessService,
            IMapper mapper, IWebHostEnvironment hostEnvironment) 
            : base(bookBusinessService, mapper, hostEnvironment, userBusinessService)
        { }

        /// <summary>
        /// Получить список книг из внутренней БД
        /// </summary>
        /// <param name="value">Значение поисковика</param>
        [HttpGet("books/byvalue")]
        public async Task<List<BcBookDto>> BooksByValue(string value)
        {
            var books = await bookBusinessService.GetBooksByValue(value);
            return books.Take(50).ToList();
        }

        /// <summary>
        /// Запрос на автозаполнение книги из внутренней БД
        /// </summary>
        /// <param name="id">Идентификатор книги</param>
        [HttpGet("books/auto/add")]
        public async Task<int> AddAutoBook(int id)
        {
            var user = await userBusinessService.GetUserByEmail(User.Identity.Name);
            var bcbook = await bookBusinessService.GetBcBook(id);
            var book = mapper.Map<BcBookDto, BookDto>(bcbook);
            book.Id = 0;
            book.UserId = user.Id;
            return await bookBusinessService.AddBook(book);
        }

        /// <summary>
        /// Запрос на автозаполнение из внешней БД Bookcity
        /// </summary>
        /// <param name="href">Ссылка книги</param>
        [HttpGet("books/bc/add")]
        public async Task<int> AddBcBook(string href)
        {
            try
            {
                var path = "https://murmuring-savannah-25756.herokuapp.com/ebs/bookcity/details/" + href;
                var user = await userBusinessService.GetUserByEmail(User.Identity.Name);
                var client = new HttpClient();
                var response = await client.GetAsync(path);
                var result = response.Content.ReadAsStringAsync().Result;
                var book = JsonConvert.DeserializeObject<BookDto>(result);
                book.UserId = user.Id;
                await bookBusinessService.AddBook(book);
                return 1;
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                return -1;
            }
        }

        /// <summary>
        /// Запрос на заполнение книги вручную
        /// </summary>
        /// <param name="title">Титул книги</param>
        /// <param name="author">Автор книги</param>
        /// <param name="desc">Описание книги</param>
        /// <param name="rate">Рейтинг книги</param>
        /// <returns></returns>
        [HttpGet("books/manual/add")]
        public async Task<int> AddManualBook(string title, string author, string desc, int rate)
        {
            var user = await userBusinessService.GetUserByEmail(User.Identity.Name);
            var book = new BookDto()
            {
                Title = title,
                Author = author,
                Description = desc,
                Rate = rate
            };
            book.UserId = user.Id;
            return await bookBusinessService.AddBook(book);
        }

        /// <summary>
        /// Поиск книг по ключевому тексту
        /// </summary>
        /// <param name="search">Ключевой текст</param>
        [HttpGet("books/index")]
        public async Task<IActionResult> GetBooksBySearch(string search, int minCount = 0)
        {
            var books = await bookBusinessService.GetBooksBySearchValue(search);
            books = GetMinCountOfBooks(minCount, books);
            var booksVM = new List<BookListViewModel>();
            foreach (var book in books)
            {
                var entity = mapper.Map<BookDto, BookListViewModel>(book);
                entity.UserEmail = book.User.Email;
                booksVM.Add(entity);
            }
            return Ok(booksVM);
        }

        /// <summary>
        /// Получить список книг по идентификатору пользователя
        /// </summary>
        [HttpGet("books/user/{id}")]
        public async Task<IActionResult> GetBooksByUserId(int id)
        {
            var books = await bookBusinessService.GetBooksByUserId(id);
            var booksVM = mapper.Map<List<BookDto>, List<BookListViewModel>>(books);
            return Ok(new { books = booksVM });
        }

        /// <summary>
        /// Получить количество книг в библиотеке по идентификатору пользователя
        /// </summary>
        [HttpGet("books/count/user/{id}")]
        public async Task<IActionResult> GetBooksCountByUserId(int id)
        {
            var books = await bookBusinessService.GetBooksByUserId(id);
            return Ok(new { count = books.Count });
        }

        [HttpGet("books/bookTop")]
        public async Task<IActionResult> GetTopBooksByClickCount()
        {
            var books = await bookBusinessService.GetBooks();
            var topBooks = books.OrderByDescending(s => s.СlickCount).Take(3).ToList();
            var booksVM = mapper.Map<List<BookDto>, 
                List<BookListViewModel>>(topBooks);
            return Ok(new { books = booksVM });
        }

        private List<BookDto> GetMinCountOfBooks(int minCount, List<BookDto> books)
        {
            if(minCount > 0)
            {
                return books.Take(minCount).ToList();
            }

            return books;
        }
    }
}

UserInterface/Controllers/Api/UserController.cs
using AutoMapper;
using BusinessLogic.Dto;
using BusinessLogic.Services.BusinessService;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using UserInterface.ViewModels;
using UserInterface.ViewModels.Entities;
namespace UserInterface.Controllers.Api
{
    public class UserController : EbsApiController
    {
        public UserController(IUserBusinessService userBusinessService,
            IMapper mapper, IWebHostEnvironment hostEnvironment) : base(userBusinessService, mapper, hostEnvironment)
        { }

        /// <summary>
        /// Список всех пользователей
        /// </summary>
        [HttpGet("users")]
        public async Task<IActionResult> Get(int minCount = 0)
        {
            var users = await userBusinessService.GetUsers();
            return GetMinCountOfUsers(minCount, users);
        }

        private OkObjectResult GetMinCountOfUsers(int minCount, List<UserDto> users)
        {
            if (minCount > 0)
            {
                return Ok(mapper.Map<List<UserDto>,
                    List<UserListViewModel>>(users).Take(minCount).ToList());   
            }

            return Ok(mapper.Map<List<UserDto>, List<UserListViewModel>>(users));
        }

        /// <summary>
        /// Поиск пользователей по ключевому тексту
        /// </summary>
        /// <param name="search">Ключевой текст</param>
        [HttpGet("users/list")]
        public async Task<IActionResult> GetUsersBySearch(string search)
        {
            var users = await userBusinessService.GetUsersBySearch(search);
            var usersVM = mapper.Map<List<UserDto>, List<UserViewModel>>(users);
            var me = usersVM.Where(s => s.Email == User.Identity.Name).FirstOrDefault();
            if (me != null)
                usersVM.Remove(me);
            return Ok(usersVM);
        }

        /// <summary>
        /// Получить текущего аутентифицированного пользователя
        /// </summary>
        [HttpGet("users/me")]
        public async Task<IActionResult> GetCurrentUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userEmail = User.Identity.Name;
                var user = await userBusinessService.GetUserByEmail(userEmail);
                var userVM = mapper.Map<UserDto, UserViewModel>(user);
                return Ok(new { data = userVM, isSuccess = true });
            }
            return Ok(new { isSuccess = false });
        }

        /// <summary>
        /// Пользователи, у которых много книг
        /// </summary>
        [HttpGet("users/userTop")]
        public async Task<IActionResult> GetUsersOrderDescByBookCount()
        {
            var users = await userBusinessService.GetUsers();
            var topUsers = users.OrderByDescending(s => s.Books.Count).Take(3).ToList();
            var usersVM = mapper.Map<List<UserDto>, List<UserViewModel>>(topUsers);
            return Ok(new { data = usersVM } );
        }

        /// <summary>
        /// Скачать файл с тренингом
        /// </summary>
        [HttpGet("downloadTraining")]
        public IActionResult DownloadTraining()
        {
            var fileName = "EBS_Introduction.pdf";
            var filePath = $"~/pdf/{fileName}";
            Response.Headers.Add("Content-Disposition", $"inline; filename={fileName}");
            return File(filePath, "application/pdf");
        }
    }
}

UserInterface/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BusinessLogic.Dto;
using BusinessLogic.Services.BusinessService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserInterface.Controllers.Base;
using UserInterface.ViewModels;
using Common.BookTransaction;

namespace UserInterface.Controllers
{
    [Authorize]
    public class TransactionController : BaseMvcController
    {
        private readonly IBookBusinessService bookBusinessService;
        private readonly IUserBusinessService userBusinessService;

        public TransactionController(IBookBusinessService bookBusinessService,
            IMapper mapper, IUserBusinessService userBusinessService,
            IWebHostEnvironment hostEnvironment) : base(mapper, hostEnvironment)
        {
            this.bookBusinessService = bookBusinessService;
            this.userBusinessService = userBusinessService;
        }

        /// <summary>
        /// Список транзакции пользователя
        /// </summary>
        /// <param name="id">Идентификатор пользователя</param>
        public async Task<IActionResult> Index(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var transactions = await bookBusinessService.GetBookTransactionsByBorrowerId(id);
            var transactionsVM = mapper.Map<List<BookTransactionDto>, 
                List<BookTransactionViewModel>>(transactions);
            var user = await this.userBusinessService.GetUserById(id);

            if(user == null)
            {
                return NotFound();
            }

            ViewBag.Email = user.Email;
            ViewBag.Id = user.Id;

            return View(transactionsVM);
        }

        /// <summary>
        /// Запрос на одолжение книги
        /// </summary>
        /// <param name="id">Идентификатор книги</param>
        [HttpGet]
        public async Task<IActionResult> Borrow(int id)
        {
            var book = await bookBusinessService.GetBookById(id, null, false);
            var currentUser = await userBusinessService.GetUserByEmail(User.Identity.Name);
            var transactions = await bookBusinessService.GetBookTransactionsByBookId(id);
            var transactionsVM = mapper.Map<List<BookTransactionDto>, 
                List<BookTransactionViewModel>>(transactions);
            ViewData["Transactions"] = transactionsVM;
            ViewData["Title"] = book.Title;

            if (book.UserId == currentUser.Id)
            {
                return NotFound();
            }

            var transaction = new BookTransactionViewModel()
            {
                Id = Guid.NewGuid().ToString(),
                BorrowerId = currentUser.Id,
                OwnerId = book.UserId,
                BookId = id,
                BorrowStartDate = DateTime.Now,
                BorrowEndDate = DateTime.Now
            };

            return View(transaction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Borrow(string id, BookTransactionViewModel model)
        {
            if(id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var start = model.BorrowStartDate;
                    var end = model.BorrowEndDate;
                    var difference = (end - start).Days;
                    const int maxDays = 7;
                    const int minDays = 1;
                    var now = DateTime.Now.Date;
                    if((start.Date >= now && now <= end.Date) && 
                        (minDays <= difference && difference <= maxDays))
                    {
                        if(await bookBusinessService.IsThisBookFree(model.BookId, start, end))
                        {
                            var dtoModel = mapper.Map<BookTransactionViewModel, BookTransactionDto>(model);
                            dtoModel.CreatedDate = DateTime.Now;
                            dtoModel.IsSuccess = null;
                            dtoModel.OwnerAgreed = null;

                            await bookBusinessService.CreateTransaction(dtoModel);

                            return RedirectToAction("Index", new { id = dtoModel.BorrowerId });
                        }
                        else
                        {
                            ModelState.AddModelError("", "Книга в это время занята, выберите другое время");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Бронировать книгу можно, начиная либо с текущей даты, либо с любой даты не больше недели.");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
            }

            var transactions = await bookBusinessService.GetBookTransactionsByBookId(model.BookId);
            var transactionsVM = mapper.Map<List<BookTransactionDto>, 
                List<BookTransactionViewModel>>(transactions);
            ViewBag.Transactions = transactionsVM;
            return View(model);
        }

        /// <summary>
        /// Страница с запросами на одолжение
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Requests()
        {
            var user = await userBusinessService.GetUserByEmail(User.Identity.Name);

            var transactions = await bookBusinessService.GetBookTransactionsByOwnerId(user.Id);

            var requestsVM = mapper.Map<List<BookTransactionDto>, 
                List<BookTransactionViewModel>>(transactions);
            return View(requestsVM.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Control(int id)
        {
            var book = await bookBusinessService.GetBookById(id, null);
            if(book != null && book.User.Email == User.Identity.Name)
            {
                var transactions = await bookBusinessService.GetBookTransactionsByBookId(id);
                var transactionsVM = mapper.Map<List<BookTransactionDto>,
                    List<BookTransactionViewModel>> (transactions);
                return View(transactionsVM);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> ControlPost(int BookId, string Id, int Status, string Comment)
        {
            await bookBusinessService.BookTransactionStatusEdit(Id, (TransactionStatus)Status, Comment);
            return RedirectToAction("Control", new { id = BookId });
        }
    }
}

UserInterface/Views/Book/ByUser.cshtml
@model List<UserInterface.ViewModels.Entities.BookViewModel>
@{
    ViewData["Title"] = "Books";
}
<section style="padding-top:50px;">
    <div class="container pt-5">
        <a class="btn btn-primary mb-3" asp-controller="User" asp-action="Index">Back</a>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">EBookSharing</a></li>
                <li class="breadcrumb-item">ELibrary</li>
                <li class="breadcrumb-item active" aria-current="page">@ViewBag.Email</li>
            </ol>
        </nav>
        @if(User.Identity.Name == ViewBag.Email)
        {
            <a asp-controller="Book" asp-action="Create" class="btn btn-success mb-3">Add book <i class="fa fa-plus"></i></a>
        }
        <div class="row">
            @await Html.PartialAsync("../Shared/PartialViews/_BookComponent.cshtml", Model)
        </div>
    </div>
</section>

UserInterface/Views/Book/Delete.cshtml
@model UserInterface.ViewModels.Entities.BookViewModel

@{
    ViewData["Title"] = "Delete";
}

<section style="padding-top:50px">
    <div class="container pt-5">
        <h1>Delete</h1>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Book</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Author)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Author)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Rate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Rate)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="User.Id" />
                <input type="hidden" asp-for="User.Email"  />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        </div>

    </div>
</section>

UserInterface/Views/Book/Details.cshtml
@model UserInterface.ViewModels.Entities.BookViewModel
@{
    ViewData["Title"] = "Details";
    var image = "/img/" + (Model.ImageSource != null ? Model.ImageSource : "no-book.png");
    if (Model.ImageSource != null && Model.ImageSource.Contains("http")) image = Model.ImageSource;
}
<section style="padding-top:50px;">
    <div class="container pt-5 pb-5">
        <a class="btn btn-primary mb-3" asp-controller="Book" asp-action="ByUser" asp-route-id="@Model.UserId">Back</a>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">EBookSharing</a></li>
                <li class="breadcrumb-item"><a asp-action="ByUser" asp-route-id="@Model.UserId">ELibrary</a></li>
                <li class="breadcrumb-item active" aria-current="page">Details</li>
                <li class="breadcrumb-item active" aria-current="page">@Model.Title</li>
            </ol>
        </nav>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <img src="@image" width="100%" />
                @if (ViewBag.IsCurrentUser)
                {
                    <a asp-controller="Book" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-block mt-3 mb-3">Edit</a>
                    <a asp-controller="Transaction" asp-action="Control" asp-route-id="@Model.Id" class="btn btn-outline-success btn-block mt-3">Control</a>
                }
            </div>
            <div class="col-md-8">
                <p><b>Title:</b> @Model.Title</p>
                <p><b>Author:</b> @Model.Author</p>
                <p><b>Description:</b></p>
                <p>@Model.Description</p>
                <p><b>Rate:</b> @Model.Rate</p>
                <p>
                    <b>Is Borrowed:</b>
                    @if (Model.IsBorrowed)
                    {
                        <span class="badge badge-pill badge-danger">It's busy now</span>
                    }
                    else
                    {
                        <span class="badge badge-pill badge-success">It's free</span>
                    }
                </p>
                <p>
                    <b>Is book in good condition:</b>
                    @if (Model.InGoodCondition)
                    {
                        <span class="badge badge-pill badge-success">Yes</span>
                    }
                    else
                    {
                        <span class="badge badge-pill badge-danger">No</span>
                    }
                </p>
                <p>
                    <b>Is book painted:</b>
                    @if (Model.IsPainted)
                    {
                        <span class="badge badge-pill badge-danger">Yes</span>
                    }
                    else
                    {
                        <span class="badge badge-pill badge-success">No</span>
                    }
                </p>
                @if (!ViewBag.IsCurrentUser)
                {
                    <a href="#" class="btn btn-primary btn-block">Message User</a>
                    <a href="#" class="btn btn-success btn-block">Borrow</a>
                }
            </div>
        </div>
    </div>
</section>

UserInterface/Views/Book/Edit.cshtml
@model UserInterface.ViewModels.Entities.BookViewModel

@{
    ViewData["Title"] = "Edit";
    var image = "/img/" + (Model.ImageSource != null ? Model.ImageSource : "no-book.png");
    if (Model.ImageSource != null && Model.ImageSource.Contains("http")) image = Model.ImageSource;
}

<section style="padding-top:50px;">
    <div class="container pt-5 pb-5">
        <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary mb-3">Back</a>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">EBookSharing</a></li>
                <li class="breadcrumb-item"><a asp-action="ByUser" asp-route-id="@Model.UserId">ELibrary</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
                <li class="breadcrumb-item active" aria-current="page">@Model.Id</li>
            </ol>
        </nav>
        <h1>Edit</h1>
        <hr />
        <div class="row">
            <div class="col-md-6 mb-3">
                <form enctype="multipart/form-data" asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Author" class="control-label"></label>
                        <input asp-for="Author" class="form-control" />
                        <span asp-validation-for="Author" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea class="form-control" asp-for="Description" rows="5"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Rate" class="control-label"></label>
                        <input asp-for="Rate" class="form-control" />
                        <span asp-validation-for="Rate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="IsPainted" class="control-label"></label>
                        @Html.EditorFor(x => x.IsPainted)
                        <span asp-validation-for="IsPainted" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="InGoodCondition" class="control-label"></label>
                        @Html.EditorFor(x => x.InGoodCondition)
                        <span asp-validation-for="InGoodCondition" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Image" class="control-label"></label>
                        <div class="custom-file">
                            <input asp-for="Image" class="form-control custom-file-input" />
                            <label class="custom-file-label">Choose file...</label>
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                    </div>
                    @if (Model.ImageSource != null)
                    {
                        <div class="form-group">
                            <label class="text-danger">
                                <input asp-for="RemoveImage" /> Remove image
                            </label>
                            <span asp-validation-for="RemoveImage" class="text-danger"></span>
                        </div>
                    }
                    <div class="form-group">
                        <input asp-for="UserId" class="form-control" type="hidden" />
                        <input type="hidden" asp-for="ImageSource" value="@Model.ImageSource" />
                    </div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-success btn-block" />
                    </div>
                </form>
            </div>
            <div class="col-md-6 mb-3 text-center">
                <img src="@image" width="50%" style="margin:0 auto !important" />
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UserInterface/Views/Book/Index.cshtml
@model List<UserInterface.ViewModels.Entities.BookViewModel>
@{
    ViewData["Title"] = "Books";
}

<section style="padding-top:50px">
    <div class="container pt-5">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-action="Index" asp-controller="User">EBookSharing</a></li>
                <li class="breadcrumb-item active" aria-current="page">Books</li>
            </ol>
        </nav>
        <div class="row">
            <div class="col-md-12">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="ebs-search-value" placeholder="Search book" value="@ViewBag.Search">
                    <div class="input-group-append">
                        <button class="btn btn-outline-success" id="ebs-search-submit" type="button">Find it</button>
                    </div>
                </div>
                <div class="row" id="ebs-target-list">
                    @await Html.PartialAsync("../Shared/PartialViews/_BookComponent.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    <script src="~/js/app/bookController.js"></script>
}