UserInterface/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BusinessLogic.Dto;
using BusinessLogic.Services.BusinessService;
using Microsoft.AspNetCore.Mvc;
using UserInterface.ViewModels;

namespace UserInterface.Controllers
{
    public class AdminController : Controller
    {
        private readonly IBookBusinessService bookBusinessService;
        private readonly IUserBusinessService userBusinessService;
        private readonly IMapper mapper;

        public AdminController(IMapper mapper, IBookBusinessService bookBusinessService,
            IUserBusinessService userBusinessService)
        {
            this.bookBusinessService = bookBusinessService;
            this.userBusinessService = userBusinessService;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

UserInterface/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.Services.BusinessService;
using Microsoft.AspNetCore.Hosting;
using AutoMapper;
using UserInterface.ViewModels.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;
using UserInterface.ViewModels;
using BusinessLogic.Dto;
using UserInterface.Controllers.Base;

namespace UserInterface.Controllers
{
    [Authorize]
    public class BookController : BaseMvcController
    {
        private readonly IUserBusinessService userBusinessService;
        private readonly IBookBusinessService bookBusinessService;

        public BookController(IBookBusinessService bookBusinessService, IMapper mapper,
            IWebHostEnvironment hostEnvironment, IUserBusinessService userBusinessService) 
            : base(mapper, hostEnvironment)
        {
            this.bookBusinessService = bookBusinessService;
            this.userBusinessService = userBusinessService;
        }

        /// <summary>
        /// Страница с поисковиком
        /// </summary>
        /// <param name="search">Объект поиска</param>
        public async Task<IActionResult> Index(string search)
        {
            var books = await bookBusinessService.GetBooksBySearchValue(search);
            var booksVM = mapper.Map<List<BookDto>, List<BookViewModel>>(books);
            ViewBag.Search = search;
            return View(booksVM);
        }

        /// <summary>
        /// Детальная информация о книге
        /// </summary>
        /// <param name="id">Идентификатор книги</param>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await userBusinessService.GetUserByEmail(User.Identity.Name);
            var book = await bookBusinessService.GetBookById(id, currentUser.Id);
            var bookVM = mapper.Map<BookDto, BookViewModel>(book);
            var user = await userBusinessService.GetUserById(book.UserId);
            ViewBag.IsCurrentUser = user.Email == User.Identity.Name;
            return View(bookVM);
        }

        /// <summary>
        /// Получить список книг по пользователю
        /// </summary>
        /// <param name="id">Идентификатор пользователя</param>
        public async Task<IActionResult> ByUser(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await userBusinessService.GetUserById(id);
            if(user == null)
            {
                return NotFound();
            }

            var books = await bookBusinessService.GetBooksByUserId(id);
            var booksVM = mapper.Map<List<BookDto>, List<BookViewModel>>(
                books.OrderBy(s => s.CreatedDate).ToList());
            ViewBag.Email = user.Email;
            return View(booksVM);
        }


        /// <summary>
        /// Создать книгу
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var user = await userBusinessService.GetUserByEmail(User.Identity.Name);
            if(user == null)
            {
                return NotFound();
            }

            ViewBag.UserId = user.Id;
            return View(new BookViewModel());
        }

        /// <summary>
        /// Редактировать книгу
        /// </summary>
        /// <param name="id">Идентификатор книги</param>
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var book = await bookBusinessService.GetBookById(id, null, false);

            if(book == null)
            {
                return NotFound();
            }

            var user = await userBusinessService.GetUserById(book.UserId);
            if(user.Email != User.Identity.Name)
            {
                return RedirectToAction("Index", "User");
            }

            var bookVM = mapper.Map<BookDto, BookViewModel>(book);
            return View(bookVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var entity = await bookBusinessService.GetBookById(model.Id, null, false);
                    entity = mapper.Map(model, entity);

                    if (model.Image != null)
                        entity.ImageSource = CreateFile(model.Image.FileName, model.Image);

                    if (model.RemoveImage)
                        entity.ImageSource = null;

                    await bookBusinessService.UpdateBook(entity);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await BookExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = model.Id });
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await bookBusinessService.GetBookById(id, null, false);

            if (book == null)
            {
                return NotFound();
            }

            var user = await userBusinessService.GetUserById(book.UserId);
            if (user.Email != User.Identity.Name)
            {
                return RedirectToAction("Index", "User");
            }

            var bookVM = mapper.Map<BookDto, BookViewModel>(book);
            return View(bookVM);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, BookViewModel model)
        {
            if(id != model.Id)
            {
                return NotFound();
            }

            var entity = await bookBusinessService.GetBookById(model.Id, null, false);

            if(entity.User.Email != User.Identity.Name)
            {
                return NotFound();
            }

            await bookBusinessService.DeleteBook(entity);

            return RedirectToAction("ByUser", new { id = entity.User.Id });
        }

        /// <summary>
        /// Проверка на наличие книги
        /// </summary>
        /// <param name="id">Идентификатор книги</param>
        /// <returns></returns>
        private async Task<bool> BookExists(int id)
        {
            return await bookBusinessService.GetBookById(id, null) != null;
        }
    }
}

UserInterface/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BusinessLogic.Dto;
using BusinessLogic.Services.BusinessService;
using DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using UserInterface.Controllers.Base;
using UserInterface.ViewModels;

namespace UserInterface.Controllers
{
    [Authorize]
    public class MessageController : BaseMvcController
    {
        private readonly IUserBusinessService userBusinessService;
        private readonly IMessageBusinessService messageBusinessService;

        public MessageController(IUserBusinessService userBusinessService,
            IMessageBusinessService messageBusinessService, IMapper mapper, 
            IWebHostEnvironment hostEnvironment) : base(mapper, hostEnvironment)
        {
            this.userBusinessService = userBusinessService;
            this.messageBusinessService = messageBusinessService;
        }

        /// <summary>
        /// Список диалогов
        /// </summary>
        public async Task<IActionResult> Index()
        {
            var dialogs = await messageBusinessService.GetDialogs(User.Identity.Name);
            var dialogsVM = mapper.Map<List<DialogControlDto>, List<DialogViewModel>>(dialogs);
            return View(dialogsVM.OrderByDescending(s => s.LastMessageDate).ToList());
        }

        /// <summary>
        /// Диалог по пользователю (получатель)
        /// </summary>
        /// <param name="id">Идентификатор получателя</param>
        public async Task<IActionResult> DialogByUser(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await userBusinessService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            var me = await userBusinessService.GetUserByEmail(User.Identity.Name);
            var dialog = await messageBusinessService.GetDialogControlByInterlocutorsId(me.Id, user.Id);

            if (dialog == null)
            {
                dialog = new DialogControlDto()
                {
                    FirstInterlocutorEmail = User.Identity.Name,
                    FirstInterlocutorId = me.Id,
                    SecondInterlocutorEmail = user.Email,
                    SecondInterlocutorId = user.Id
                };

                dialog.Id = await messageBusinessService.CreateDialogControl(dialog);
            }

            return RedirectToAction("Dialog", new { id = dialog.Id });
        }

        /// <summary>
        /// Страница диалог с пользователем
        /// </summary>
        /// <param name="id">Идентификатор диалога</param>
        public async Task<IActionResult> Dialog(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var dialog = await messageBusinessService.GetDialogControlById(id);
            if (dialog == null)
            {
                return NotFound();
            }

            var userId = dialog.FirstInterlocutorEmail == User.Identity.Name ? 
                dialog.SecondInterlocutorId : dialog.FirstInterlocutorId;

            var user = await userBusinessService.GetUserById(userId);
            var me = await userBusinessService.GetUserByEmail(User.Identity.Name);

            ViewBag.Receiver = user;
            ViewBag.Me = me;
            ViewBag.DialogId = id;

            var dialogVM = mapper.Map<DialogControlDto, DialogViewModel>(dialog);
            dialogVM.Messages = await messageBusinessService.GetMessagesByDialogId(id);

            return View(dialogVM);
        }
    }
}

UserInterface/Views/Shared/PartialViews/_BookComponent.cshtml
@model List<UserInterface.ViewModels.Entities.BookViewModel>
<style>.badge {top: 10px;left: 10px;padding: 10px;position: absolute;}</style>
@if (Model.Count < 1)
{
    <div class="col-md-12 text-center pt-5 mt-5">
        <h3 class="display-3">There is no one book :(</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
    </div>
}
else
{
    foreach (var book in Model)
    {
        var image = "/img/" + (book.ImageSource != null ? book.ImageSource : "no-book.png");
        if (book.ImageSource != null && book.ImageSource.Contains("http")) image = book.ImageSource;

        <div class="col-md-4 mb-3">
            <div class="card" style="width: 18rem;">
                @if (book.IsBorrowed)
                {
                    <span class="badge badge-pill badge-danger">Borrowed</span>
                }
                else
                {
                    <span class="badge badge-pill badge-success">Free</span>
                }
                <img src="@image" class="card-img-top" width="100%">
                <div class="card-body">
                    <h5 class="card-title">@book.Title</h5>
                    <p>@book.Author</p>
                </div>
                <div class="card-footer">
                    <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id" class="btn btn-primary pull-right">Details</a>
                    @if (book.User.Email != User.Identity.Name)
                    {
                        <a asp-controller="Transaction" asp-action="Borrow" asp-route-id="@book.Id" class="btn btn-success pull-right mr-2">Borrow</a>
                    }
                    else
                    {
                        <a asp-controller="Book" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-outline-primary pull-right mr-2">Edit</a>
                        <a asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-outline-danger pull-right mr-2">Delete</a>
                    }
                </div>
            </div>
        </div>
    }
}

UserInterface/Views/Shared/PartialViews/_MenuComponent.cshtml
@model int

<div class="ebs-left-menu mb-4">
    <p class="border-bottom"><a asp-controller="User" asp-action="Details" asp-route-id="@Model"><i class="fa fa-user-circle mr-2"></i> My Account</a></p>
    <p class="border-bottom"><a asp-controller="User" asp-action="List"><i class="fa fa-users mr-2"></i> Users</a></p>
    <p class="border-bottom"><a asp-controller="Message" asp-action="Index"><i class="fa fa-comments-o mr-2"></i> Messages <span id="signalr-messages" class="badge badge-pill badge-light ml-2 mb-2"></span></a></p>
    <p class="border-bottom"><a asp-controller="Book" asp-action="ByUser" asp-route-id="@Model"><i class="fa fa-book mr-2"></i> ELibrary</a></p>
    <p class="border-bottom"><a asp-controller="Book" asp-action="Index"><i class="fa fa-institution mr-2"></i> Books</a></p>
    <p class="border-bottom"><a asp-controller="Transaction" asp-action="Index" asp-route-id="@Model"><i class="fa fa-calendar mr-2"></i> Transactions</a></p>
    <p class="border-bottom"><a asp-controller="Transaction" asp-action="Requests"><i class="fa fa-cubes mr-1"></i> Requests <span id="signalr-requests" class="badge badge-pill badge-light ml-2 mb-2"></span></a></p>
    <p><a asp-controller="User" asp-action="Logout"><i class="fa fa-sign-out mr-2"></i> Logout</a></p>
</div>
@if (ViewData["Role"].ToString() == "admin")
{
    <div class="ebs-left-menu mb-4">
        <h4 class="text-light mb-3">Admin panel</h4>
        <p class="border-bottom"><a asp-controller="Admin" asp-action="Index"><i class="fa fa-book mr-2"></i> Windows</a></p>
        @*<p class="border-bottom"><a href="#"><i class="fa fa-users mr-2"></i> Users</a></p>
        <p class="border-bottom"><a href="#"><i class="fa fa-book mr-2"></i> Books</a></p>*@
    </div>
}

UserInterface/Views/Shared/PartialViews/_RequestComponent.cshtml
@model List<UserInterface.ViewModels.BookTransactionViewModel>
<style>
    .progress-success {
        position: absolute;
        width: 100%;
        height: 5px;
        bottom: 0;
        left: 0;
        background-color: green;
    }

    .progress-danger {
        position: absolute;
        width: 100%;
        height: 5px;
        bottom: 0;
        left: 0;
        background-color: red;
    }

    .progress-warning {
        position: absolute;
        width: 100%;
        height: 5px;
        bottom: 0;
        left: 0;
        background-color: yellow;
    }
</style>
@if (Model.Count < 1)
{
    <div class="col-md-12 text-center pt-5">
        <h1>Empty requests</h1>
    </div>
}
else
{
    @foreach (var transaction in Model)
    {
        var image = "/img/" + (transaction.Book.ImageSource != null ? transaction.Book.ImageSource : "no-book.png");
        if (transaction.Book.ImageSource != null && transaction.Book.ImageSource.Contains("http")) image = transaction.Book.ImageSource;
        <div class="col-md-6 mb-3 pr-4 pl-4 pt-4 pb-5" id="ebs-@transaction.Id.ToString()">
            <div class="row bg-light">
                <div class="col-md-4 mt-3">
                    <img src="@image" width="100%" />
                </div>
                <div class="col-md-8 mt-3">
                    <h4>@transaction.Book.Title</h4>
                    <p><b>Start:</b> @transaction.BorrowStartDate.Date.ToString("dd/MM/yyyy")</p>
                    <p><b>End:</b> @transaction.BorrowEndDate.Date.ToString("dd/MM/yyyy")</p>
                    <button class="btn btn-outline-success ebs-btn-accept" data-id="@transaction.Id.ToString()">Принять</button>
                    <button class="btn btn-outline-danger ebs-btn-cancel" data-id="@transaction.Id.ToString()">Отклонить</button>
                    <a class="btn btn-primary" asp-controller="User" asp-action="Details" asp-route-id="@transaction.BorrowerId">Должник</a>
                </div>
                <div class="col-md-12 mt-4">
                    @if (transaction.IsSuccess == null)
                    {
                        <div class="progress-warning"></div>
                    }
                    else if (transaction.IsSuccess == false)
                    {
                        <div class="progress-danger"></div>
                    }
                    else
                    {
                        <div class="progress-success"></div>
                    }
                </div>
            </div>
        </div>
    }
}

UserInterface/Views/Shared/PartialViews/_TransactionComponent.cshtml
@model List<UserInterface.ViewModels.BookTransactionViewModel>
<style>
    .progress-success {
        position: absolute;
        width: 100%;
        height: 5px;
        bottom: 0;
        left: 0;
        background-color: green;
    }

    .progress-danger {
        position: absolute;
        width: 100%;
        height: 5px;
        bottom: 0;
        left: 0;
        background-color: red;
    }

    .progress-warning {
        position: absolute;
        width: 100%;
        height: 5px;
        bottom: 0;
        left: 0;
        background-color: yellow;
    }
</style>
@if (Model.Count < 1)
{
    <div class="col-md-12 text-center pt-5">
        <h1>Empty transactions</h1>
    </div>
}
else
{
    @foreach (var transaction in Model)
    {
        var image = "/img/" + (transaction.Book.ImageSource != null ? transaction.Book.ImageSource : "no-book.png");
        if (transaction.Book.ImageSource != null && transaction.Book.ImageSource.Contains("http")) image = transaction.Book.ImageSource;
        string hasSeen = transaction.OwnerHasSeen ? "Владелец прочитал," : "Владелец ещё не прочитал,";
        string isSuccess = "";
        switch (transaction.IsSuccess)
        {
            case null:
                isSuccess = "В процессе";
                break;
            case false:
                isSuccess = "Провал";
                break;
            case true:
                isSuccess = "Успешно";
                break;
        }
        string isAgreed = "и неизвестно может ли одолжить";
        if (transaction.OwnerHasSeen && transaction.OwnerAgreed == true) isAgreed = "и согласился одолжить";
        if (transaction.OwnerHasSeen && transaction.OwnerAgreed == false) isAgreed = "и не согласился одолжить";

        <div class="col-md-6 mb-3 pr-4 pl-4 pt-4 pb-5">
            <div class="row bg-light">
                <div class="col-md-4 mt-3">
                    <img src="@image" width="100%" />
                </div>
                <div class="col-md-8 mt-3">
                    <h4>@transaction.Book.Title</h4>
                    <p><b>Start:</b> @transaction.BorrowStartDate.Date.ToString("dd/MM/yyyy")</p>
                    <p><b>End:</b> @transaction.BorrowEndDate.Date.ToString("dd/MM/yyyy")</p>
                    <p><b>Статус:</b> @isSuccess</p>
                    <p>@hasSeen @isAgreed</p>
                    <a class="btn btn-outline-primary" asp-controller="User" asp-action="Details" asp-route-id="@transaction.OwnerId">Владелец</a>
                    @*<a class="btn btn-outline-success" asp-controller="User" asp-action="Details" asp-route-id="@transaction.BorrowerId">Должник</a>*@
                </div>
                <div class="col-md-12 mt-4">
                    @if (transaction.IsSuccess == null)
                    {
                        <div class="progress-warning"></div>
                    }
                    else if (transaction.IsSuccess == false)
                    {
                        <div class="progress-danger"></div>
                    }
                    else
                    {
                        <div class="progress-success"></div>
                    }
                </div>
            </div>
        </div>
    }
}

UserInterface/Views/Shared/PartialViews/_UserComponent.cshtml
@model List<UserInterface.ViewModels.Entities.UserViewModel>
@if (Model.Count > 0)
{
    <div class="row" id="ebs-target-list">
        @foreach (var user in Model)
        {
            var image = user.ImageSource != null ? "/img/" + user.ImageSource : "/img/no-user.png";
            <div class="col-md-12">
                <div class="row mb-3 bg-light pl-3 pr-3 pt-3 pb-3">
                    <div class="col-md-4">
                        <img src="@image" width="100%" />
                    </div>
                    <div class="col-md-8">
                        <p><b>@user.Email</b></p>
                        <a asp-controller="User" asp-action="Details" asp-route-id="@user.Id" class="btn btn-outline-primary">Visit</a>
                        <a asp-controller="Message" asp-action="DialogByUser" asp-route-id="@user.Id" class="btn btn-outline-success">Message</a>
                        <a asp-controller="Book" asp-action="ByUser" asp-route-id="@user.Id" class="btn btn-primary">ELibrary</a>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <p>No users</p>
}